### ISSUE TITLE
uprade to pegdown v1.6.0

### ISSUE THREAD

**Issue by cxwtc123** [aalmiray/markdown-gradle-plugin#23]
how about upgrade to pegdown v1.6.0?

pegdown v1.6.0 release on Sep 18, 2015, which add some useful features than v1.5.0, such as:
- Added `TASKLISTITEMS` optional extension to handle GFM style task list items 
- Added `ALL_OPTIONALS` and `ALL_WITH_OPTIONALS` extension set
- Added `EXTANCHORS` optional extension

**Comment by aalmiray** [comment]
Fixed
