### ISSUE TITLE
Configure Pegdown Timeout

### ISSUE THREAD

**Issue by kedaly** [aalmiray/markdown-gradle-plugin#27]
When trying to compile my project 

I get this
BUILD FAILED in 2s
1 actionable task: 1 executed
Error while parsing action 'Root/Sequence/ZeroOrMore/Sequence/Block/FirstOf/Para/Sequence/Inlines/Sequence/ZeroOrMore/Sequence/InlineOrIntermediateEndline/Sequence/Inline/FirstOf/NonLinkInline/SingleQuoted/Sequence/OneOrMore/Sequence/Inline/FirstOf/NonLinkInline/SingleQuoted/Sequence/OneOrMore/Sequence/Inline/FirstOf/NonLinkInline/SingleQuoted/Sequence/OneOrMore/Sequence/Inline/FirstOf/NonLinkInline/SingleQuoted/Sequence/OneOrMore/Sequence/Inline/FirstOf/NonLinkInline/SingleQuoted/Sequence/OneOrMore/Sequence/Inline/FirstOf/NonLinkInline/SingleQuoted/Sequence/OneOrMore/Sequence/Inline/FirstOf/NonLinkInline/SingleQuoted/Sequence/OneOrMore/Sequence/Inline/FirstOf/Link/FirstOf/Sequence/Label/OneOrMore/Sequence/NonAutoLinkInline/NonLinkInline/SingleQuoted/Sequence/OneOrMore/Sequence/Inline/FirstOf/NonLinkInline/SingleQuoted/Sequence/OneOrMore/Sequence/Inline/FirstOf/NonLinkInline/SingleQuoted/Sequence/OneOrMore/Sequence/Inline/Inline_Action1' at input position (line 738, pos 70):
 The amount of equity attributable to the owners of the parent. This specifically excludes non-controlling interest.</td>
                                                                     ^

org.pegdown.ParsingTimeoutException

I need a way to configure Pegdown's timeout as I have a few .md files that have html tables in them instead of markdown tables, mainly for some extra formatting on the tables.

**Comment by aalmiray** [comment]
Fixed
