### ISSUE TITLE
Replace all occurrences of '.md' and '.markdown' with '.html' before generating the html

### ISSUE THREAD

**Issue by Flowdalic** [aalmiray/markdown-gradle-plugin#7]
Would it be possible that markdown-gradle-plugin optionally replaces all occurrences of '.md' and '.markdown' with '.html' before generating the html?

I'm in the process of migrating my project documentation from html to simple markdown files. Right now the links between those files are still targeting `.html`. This makes those links work in the exported html version that I place on a web server, but does not work when viewing the markdown files on e.g. github. The solution would be to have the links point to `.md` targets, which are transformed to `.html` targets while transforming the markdown to html. Although an solution that is integrated in the markdown transformator would be preferable, I think that this would already solve my problem!

**Comment by aalmiray** [comment]
closed by #15

**Comment by Flowdalic** [comment]
Thanks so much! :-)

When please ping me when a release with this feature is available.

**Comment by madmas** [comment]
Ping :-) https://bintray.com/aalmiray/kordamp/markdown-gradle-plugin/1.0.0/view

**Comment by Flowdalic** [comment]
:tada: 

thanks
